[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://nodejs.dszcbaross.edu.hu:21111/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/users/*"
  to = "https://nodejs.dszcbaross.edu.hu:21111/users/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/admin/*"
  to = "https://nodejs.dszcbaross.edu.hu:21111/admin/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/login"
  to = "https://nodejs.dszcbaross.edu.hu:21111/login"
  status = 200
  force = true

[[redirects]]
  from = "/logout"
  to = "https://nodejs.dszcbaross.edu.hu:21111/logout"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200