[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/users/*"
  to = "https://nodejs208.dszcbaross.edu.hu/users/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/admin/*"
  to = "https://nodejs208.dszcbaross.edu.hu/admin/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/global/*"
  to = "https://nodejs208.dszcbaross.edu.hu/global/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/admin/*"
  to = "https://nodejs208.dszcbaross.edu.hu/admin/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/payments/*"
  to = "https://nodejs208.dszcbaross.edu.hu/api/payments/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/public/*"
  to = "https://nodejs208.dszcbaross.edu.hu/public/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

